refactor: literally everything

diff --git a/bin/dotfiles b/bin/dotfiles
--- a/bin/dotfiles
+++ b/bin/dotfiles
@@ -1,346 +1,355 @@
-#!/usr/bin/env bash
-[[ "$1" == "source" ]] || \
+#!/usr/bin/env sh
+#
+# My dotfiles install script
+#
+# ༼ つ ◕_◕ ༽つMUST. HAVE. DOTFILES.༼ つ ◕_◕ ༽つ
+#
+# Author: Stephen Roberts <stephenroberts@gmail.com>
+#
+# Usage: dotfiles [--help|-h]
+#
+#   See the README for documentation.
+#   https://github.com/stephencroberts/dotfiles
+#
+#   Copyright (c) 2015 Stephen Roberts
+#   Licensed under the MIT license.g
 
-echo 'Dotfiles - Stephen Roberts'
+: "${REPO:=git://github.com/stephencroberts/dotfiles.git}"
+: "${DOTFILES:=$HOME/.dotfiles}"
+: "${CACHE_FILE:=$DOTFILES/.selected}"
+: "${BACKUPS:=$DOTFILES/backups/$(date +%s)}"
 
-if [[ "$1" == "-h" || "$1" == "--help" ]]; then cat <<HELP
-
-Usage: $(basename "$0")
-
-See the README for documentation.
-https://github.com/stephencroberts/dotfiles
-
-Copyright (c) 2015 Stephen Roberts
-Licensed under the MIT license.g
-HELP
-exit; fi
-
-###########################################
-# GENERAL PURPOSE EXPORTED VARS / FUNCTIONS
-###########################################
-
-# Where the magic happens.
-export DOTFILES=~/.dotfiles
-
-# Logging stuff.
-function e_header()   { echo -e "\n\033[1m$@\033[0m"; }
-function e_success()  { echo -e " \033[1;32m✔\033[0m  $@"; }
-function e_error()    { echo -e " \033[1;31m✖\033[0m  $@"; }
-function e_arrow()    { echo -e " \033[1;34m➜\033[0m  $@"; }
-
-# For testing.
-function assert() {
-  local success modes equals actual expected
-  modes=(e_error e_success); equals=("!=" "=="); expected="$1"; shift
-  actual="$("$@")"
-  [[ "$actual" == "$expected" ]] && success=1 || success=0
-  ${modes[success]} "\"$actual\" ${equals[success]} \"$expected\""
+# Prints usage to the screen, scraped from the documentation in the script
+# header
+usage() {
+  sed -n "/^# Usage/,/^[^#]/p" "$0" | sed 's/^# \{0,1\}//g' | sed '$d'
 }
 
-# OS detection
-function is_osx() {
-  [[ "$OSTYPE" =~ ^darwin ]] || return 1
-}
-function is_ubuntu() {
-  [[ "$(cat /etc/issue 2> /dev/null)" =~ Ubuntu ]] || return 1
-}
-function get_os() {
-  for os in osx ubuntu; do
-    is_$os; [[ $? == ${1:-0} ]] && echo $os
-  done
-}
+#
+# Logging
+#
 
-function get_install_type() {
-  echo $install_type
-}
+log_header()   { printf -- '\n\033[1m%b\033[0m\n' "$@"; }
+log_success()  { printf -- ' \033[1;32m✔\033[0m  %b\n' "$@"; }
+log_error()    { printf -- ' \033[1;31m✖\033[0m  %b\n' "$@" >&2; }
+log_arrow()    { printf -- ' \033[1;34m➜\033[0m  %b\n' "$@"; }
 
-# Remove an entry from $PATH
-# Based on http://stackoverflow.com/a/2108540/142339
-function path_remove() {
-  local arg path
-  path=":$PATH:"
-  for arg in "$@"; do path="${path//:$arg:/:}"; done
-  path="${path%:}"
-  path="${path#:}"
-  echo "$path"
-}
-
-function select_menu() {
-  PS3='Selection: '
-  select opt in "${!1}"; do echo $opt; break; done
-}
-
-# Display a fancy multi-select menu.
-# Inspired by http://serverfault.com/a/298312
-function prompt_menu() {
-  local exitcode prompt choices nums i n
-  exitcode=0
-  if [[ "$2" ]]; then
-    _prompt_menu_draws "$1"
-    read -t $2 -n 1 -sp "To edit this list, press any key within $2 seconds. "
-    exitcode=$?
-    echo ""
-  fi 1>&2
-  if [[ "$exitcode" == 0 ]]; then
-    prompt="Toggle options (Separate options with spaces, ENTER when done): "
-    while _prompt_menu_draws "$1" 1 && read -rp "$prompt" nums && [[ "$nums" ]]; do
-      _prompt_menu_adds $nums
-    done
-  fi 1>&2
-  _prompt_menu_adds
-}
-
-function _prompt_menu_iter() {
-  local i sel state
-  local fn=$1; shift
-  for i in "${!menu_options[@]}"; do
-    state=0
-    for sel in "${menu_selects[@]}"; do
-      [[ "$sel" == "${menu_options[i]}" ]] && state=1 && break
-    done
-    $fn $state $i "$@"
-  done
-}
-
-function _prompt_menu_draws() {
-  e_header "$1"
-  _prompt_menu_iter _prompt_menu_draw "$2"
-}
-
-function _prompt_menu_draw() {
-  local modes=(error success)
-  if [[ "$3" ]]; then
-    e_${modes[$1]} "$(printf "%2d) %s\n" $(($2+1)) "${menu_options[$2]}")"
+# Gets the current OS
+#
+# Returns: the OS
+get_os() {
+  if [ "$(uname)" = Darwin ]; then
+    echo macos
+  elif grep 'Ubuntu' >/dev/null 2>&1 </etc/issue; then
+    echo ubuntu
+  elif [ -e /etc/alpine-release ]; then
+    echo alpine
   else
-    e_${modes[$1]} "${menu_options[$2]}"
+    log_error "OS not supported!"
+    return 1
   fi
 }
 
-function _prompt_menu_adds() {
-  _prompt_menu_result=()
-  _prompt_menu_iter _prompt_menu_add "$@"
-  menu_selects=("${_prompt_menu_result[@]}")
+# Installs git in the target OS
+#
+# Arguments:
+#   - os name
+install_git() {
+  type -p git >/dev/null 2>&1 && git --version >/dev/null || {
+    log_header "Installing git"
+    "install_git_$1"
+  }
+
+  # Check that git is installed
+  type -p git >/dev/null 2>&1 && git --version >/dev/null
 }
 
-function _prompt_menu_add() {
-  local state i n keep match
-  state=$1; shift
-  i=$1; shift
-  for n in "$@"; do
-    if [[ $n =~ ^[0-9]+$ ]] && (( n-1 == i )); then
-      match=1; [[ "$state" == 0 ]] && keep=1
+# git is already installed on MacOS
+install_git_macos() {
+  printf -- "Waiting for git to be installed. Press ENTER to continue."
+  read -r
+}
+
+# Installs git for ubuntu
+install_git_ubuntu() {
+  sudo apt-get -qq install git-core
+}
+
+install_git_alpine() {
+  apk add --update git
+}
+
+#
+# Dotfiles administrative things
+#
+
+# Download or update dotfiles
+#
+# Returns: code 1 if dotfiles were updated
+fetch_dotfiles() {
+  if [ ! -d "$DOTFILES" ]; then
+    log_header "Downloading dotfiles"
+    git clone "$REPO" "$DOTFILES"
+  else
+    log_header "Updating dotfiles"
+    cd "$DOTFILES"
+    prev_head="$(git rev-parse HEAD)"
+    git pull
+    [ "$(git rev-parse HEAD)" = "$prev_head" ]
+  fi
+}
+
+# Features menu
+
+# Prints an option as selected
+#
+# Arguments:
+#   - option
+prompt_print_selected() {
+  printf -- ' \033[1;32m✔\033[0m  %b\n' "$@"
+}
+
+# Prints an option as deselected
+#
+# Arguments:
+#   - option
+prompt_print_deselected() {
+  printf -- ' \033[1;31m✖\033[0m  %b\n' "$@"
+}
+
+# Prints a menu with selected/deselected options
+#
+# Arguments:
+#   - heading
+#   - all options
+#   - selected options
+prompt_print_menu() {
+  log_header "$1"
+
+  i=1
+  for option in $2; do
+    if echo "$3" | grep "$option" >/dev/null; then
+      prompt_print_selected "$i) $option"
+    else
+      prompt_print_deselected "$i) $option"
     fi
+    i=$((i+1))
   done
-  [[ ! "$match" && "$state" == 1 || "$keep" ]] || return
-  _prompt_menu_result=("${_prompt_menu_result[@]}" "${menu_options[i]}")
 }
 
-# Given strings containing space-delimited words A and B, "setdiff A B" will
-# return all words in A that do not exist in B. Arrays in bash are insane
-# (and not in a good way).
-# From http://stackoverflow.com/a/1617303/142339
-function setdiff() {
-  local debug skip a b
-  if [[ "$1" == 1 ]]; then debug=1; shift; fi
-  if [[ "$1" ]]; then
-    local setdiffA setdiffB setdiffC
-    setdiffA=($1); setdiffB=($2)
-  fi
-  setdiffC=()
-  for a in "${setdiffA[@]}"; do
-    skip=
-    for b in "${setdiffB[@]}"; do
-      [[ "$a" == "$b" ]] && skip=1 && break
-    done
-    [[ "$skip" ]] || setdiffC=("${setdiffC[@]}" "$a")
+# Gets an item by index (1-indexed) from a space-delimited list
+#
+# Arguments:
+#   - list
+#   - index
+#
+# Returns: the item at index
+get_item_at_index() {
+  i=1
+  for item in $1; do
+    if [ $i -eq "$2" ]; then
+      echo "$item"
+      break
+    fi
+    i=$((i+1))
   done
-  [[ "$debug" ]] && for a in setdiffA setdiffB setdiffC; do
-    echo "$a ($(eval echo "\${#$a[*]}")) $(eval echo "\${$a[*]}")" 1>&2
-  done
-  [[ "$1" ]] && echo "${setdiffC[@]}"
 }
 
-# If this file was being sourced, exit now.
-[[ "$1" == "source" ]] && return
+# Prompts the user for selections from a menu
+#
+# This function is recursive, printing the current menu as the user updates
+# selections until the user no longer makes new selections. The list of selected
+# options is returned in a named variable.
+#
+# Arguments:
+#   - heading
+#   - all menu options
+#   - selected menu options
+#   - wait time (s) for the user to interact with the menu (optional)
+#
+# Returns: the selected menu options in the variable `prompt_selections`
+prompt_menu() {
+  heading=$1
+  options=$2
+  selected=$3
+  wait=$4
 
+  prompt_print_menu "$heading" "$options" "$selected"
 
-###########################################
-# INTERNAL DOTFILES "INIT" VARS / FUNCTIONS
-###########################################
-
-# Initialize.
-init_file=$DOTFILES/.selected
-function init_files() {
-  local i f dirname oses os opt remove
-  dirname="$(dirname "$1")"
-  f=("$@")
-  menu_options=(); menu_selects=()
-  for i in "${!f[@]}"; do menu_options[i]="$(basename "${f[i]}")"; done
-  if [[ -e "$init_file" ]]; then
-    # Read cache file if possible
-    IFS=$'\n' read -d '' -r -a menu_selects < "$init_file"
-  else
-    # Otherwise default to all scripts not specifically for other OSes
-    oses=($(get_os 1))
-    for opt in "${menu_options[@]}"; do
-      remove=
-      for os in "${oses[@]}"; do
-        [[ "$opt" =~ (^|[^a-z])$os($|[^a-z]) ]] && remove=1 && break
-      done
-      [[ "$remove" ]] || menu_selects=("${menu_selects[@]}" "$opt")
-    done
+  if [ -n "$wait" ]; then
+    read -rt "$wait" -n 1 \
+      -sp "To edit this list, press any key within $wait seconds." || {
+      # Return final results
+      export prompt_selections=$selected
+      return 0
+    }
   fi
-  prompt_menu "Run the following init scripts?" $prompt_delay
+
+  # Continue asking the user for changes to the selections until they no longer
+  # enter input
+  printf -- '\r\033[K'
+  if read -rp \
+    "Toggle options (Separate options with spaces, ENTER when done): " nums \
+    && [ -n "$(echo "$nums" | xargs)" ]; then
+
+    for num in $nums; do
+
+      # Get the menu option at the index the user selected
+      option=$(get_item_at_index "$options" "$num")
+
+      # Select/deselect the option
+      if echo "$selected" | grep "$option" >/dev/null; then
+        selected=${selected//$option/}
+      else
+        selected="$selected$option "
+      fi
+    done
+
+    # Recursive! Prompt the user for more changes.
+    prompt_menu "$heading" "$options" "$selected"
+  fi
+
+  # Return final results
+  export prompt_selections=$selected
+}
+
+# Executes install scripts as selected by the user
+#
+# Arguments:
+#   - operating system
+install_things() {
+  menu_options=$(find "$DOTFILES/init" -maxdepth 1 -not -type d \
+    -exec basename {} \; | xargs)
+
+  if [ -f "$CACHE_FILE" ]; then
+    menu_selects="$(xargs <"$CACHE_FILE") "
+  fi
+
+  prompt_menu 'Suh dude. Wanna install some stuff? ¯\\\_(ツ)\_/¯' \
+    "$menu_options" "$menu_selects" 5
+
   # Write out cache file for future reading.
-  rm "$init_file" 2>/dev/null
-  for i in "${!menu_selects[@]}"; do
-    echo "${menu_selects[i]}" >> "$init_file"
-    echo "$dirname/${menu_selects[i]}"
+  echo "$prompt_selections" >"$CACHE_FILE"
+
+  for option in $prompt_selections; do
+    log_header "Installing ${option%.sh}"
+    . "$DOTFILES/init/$option" "$1" "$2"
   done
 }
 
-function init_do() {
-  e_header "Sourcing $(basename "$2")"
-  source "$2"
+# Backs up a file to the backups folder
+backup_file() {
+  # Create backup dir if it doesn't already exist.
+  [ -e "$BACKUPS" ] || mkdir -p "$BACKUPS"
+  mv "$1" "$BACKUPS"
 }
 
-# Copy files.
-function copy_header() { e_header "Copying files into home directory"; }
-function copy_test() {
-  if [[ -e "$2" && ! "$(cmp "$1" "$2" 2> /dev/null)" ]]; then
-    echo "same file"
-  elif [[ "$1" -ot "$2" ]]; then
-    echo "destination file newer"
-  fi
-}
-function copy_do() {
-  e_success "Copying ~/$1."
-  cp "$2" ~/
-}
+# Symlinks a file to HOME directory
+#
+# Arguments:
+#   - file
+link_file() {
+  base=$(basename "$1")
+  dst="$HOME/$base"
 
-# Link files.
-function link_header() { e_header "Linking files into home directory"; }
-function link_test() {
-  [[ "$1" -ef "$2" ]] && echo "same file"
-}
-function link_do() {
-  e_success "Linking ~/$1."
-  ln -sf ${2#$HOME/} ~/
-}
-
-# Copy, link, init, etc.
-function do_stuff() {
-  local base dest skip
-  local files=($DOTFILES/$1/*)
-  [[ $(declare -f "$1_files") ]] && files=($($1_files "${files[@]}"))
-  # No files? abort.
-  if (( ${#files[@]} == 0 )); then return; fi
-  # Run _header function only if declared.
-  [[ $(declare -f "$1_header") ]] && "$1_header"
-  # Iterate over files.
-  for file in "${files[@]}"; do
-    base="$(basename $file)"
-    dest="$HOME/$base"
-    # Run _test function only if declared.
-    if [[ $(declare -f "$1_test") ]]; then
-      # If _test function returns a string, skip file and print that message.
-      skip="$("$1_test" "$file" "$dest")"
-      if [[ "$skip" ]]; then
-        e_error "Skipping ~/$base, $skip."
-        continue
-      fi
-      # Destination file already exists in ~/. Back it up!
-      if [[ -e "$dest" ]]; then
-        e_arrow "Backing up ~/$base."
-        # Set backup flag, so a nice message can be shown at the end.
-        backup=1
-        # Create backup dir if it doesn't already exist.
-        [[ -e "$backup_dir" ]] || mkdir -p "$backup_dir"
-        # Backup file / link / whatever.
-        mv "$dest" "$backup_dir"
-      fi
+  if [ -e "$dst" ]; then
+    if [ "$1" -ef "$dst" ]; then
+      log_error "Skipping ~/$base, same file."
+      return 0
     fi
-    # Do stuff.
-    "$1_do" "$base" "$file"
-  done
+
+    log_arrow "Backing up ~/$base."
+    backup_file "$dst"
+  fi
+
+  log_success "Linking ~/$base."
+  ln -sf "${1#$HOME/}" ~/
+}
+
+# Sets up everything required for MacOS
+init_macos() {
+  # Install Homebrew.
+  if ! type -p brew >/dev/null; then
+    if [ ! -e /opt/homebrew/bin/brew ]; then
+      log_header "Installing Homebrew"
+      /bin/bash -c "$(curl --fail --silent --show-error --location \
+        https://raw.githubusercontent.com/Homebrew/install/HEAD/install.sh)"
+    fi
+    eval "$(/opt/homebrew/bin/brew shellenv)"
+  fi
+
+  # Exit if, for some reason, Homebrew is not installed.
+  type -p brew >/dev/null || {
+    log_error "Homebrew failed to install."
+    return 1
+  }
+
+  log_header "Updating Homebrew"
+  brew doctor || true # Brew is exiting non-zero with just warnings...
+  brew update
+}
+
+# Sets up everything required for Ubuntu
+init_ubuntu() {
+  log_header "Updating apt"
+  sudo apt-get -qq update
+  sudo apt-get -qq dist-upgrade
+}
+
+init_alpine() {
+  log_header "Updating apk"
+  apk update
+
+  log_header "Installing curl"
+  apk add curl
 }
 
 # Enough with the functions, let's do stuff.
+main() {
 
-export prompt_delay=5
+  set -e
 
-# Ensure that we can actually, like, compile anything.
-if [[ ! "$(type -p gcc)" ]] && is_osx; then
-  e_error "XCode or the Command Line Tools for XCode must be installed first."
-  exit 1
-fi
+  echo
+  echo 'Dotfiles Install Script - Stephen Roberts'
+  echo
+  echo '༼ つ ◕_◕ ༽つMUST. HAVE. DOTFILES.༼ つ ◕_◕ ༽つ'
+  echo
 
-# If Git is not installed, install it (Ubuntu only, since Git comes standard
-# with recent XCode or CLT)
-if [[ ! "$(type -p git)" ]] && is_ubuntu; then
-  e_header "Installing Git"
-  sudo apt-get -qq install git-core
-fi
-
-# If Git isn't installed by now, something exploded. We gots to quit!
-if [[ ! "$(type -p git)" ]]; then
-  e_error "Git should be installed. It isn't. Aborting."
-  exit 1
-fi
-
-# Initialize.
-if [[ ! -d $DOTFILES ]]; then
-  # $DOTFILES directory doesn't exist? Clone it!
-  new_dotfiles_install=1
-  prompt_delay=15
-  e_header "Downloading dotfiles"
-  git clone --recursive git://github.com/${github_user:-stephencroberts}/dotfiles.git $DOTFILES
-  cd $DOTFILES
-elif [[ "$1" != "restart" ]]; then
-  # Make sure we have the latest files.
-  e_header "Updating dotfiles"
-  cd $DOTFILES
-  prev_head="$(git rev-parse HEAD)"
-  git pull
-  git submodule update --init --recursive --quiet
-  if [[ "$(git rev-parse HEAD)" != "$prev_head" ]]; then
-    e_header "Changes detected, restarting script"
-    exec "$0" "restart"
+  # Show help/usage
+  if [ "$1" = -h ] || [ "$1" = "--help" ]; then
+    usage
+    return 0
   fi
-fi
 
-# Add binaries into the path
-[[ -d $DOTFILES/bin ]] && PATH=$DOTFILES/bin:$PATH
-export PATH
+  # Get the current (target) OS
+  os=$(get_os)
 
-# Tweak file globbing.
-shopt -s dotglob
-shopt -s nullglob
+  # Ensure git is installed
+  install_git "$os" || {
+    log_error "Failed to find or install git!"
+    return 1
+  }
 
-# If backups are needed, this is where they'll go.
-backup_dir="$DOTFILES/backups/$(date "+%Y_%m_%d-%H_%M_%S")/"
-backup=
-
-# Get the installation type
-options=('Minimal' 'Full')
-e_header 'Please select an installation type: '
-install_selection=$(select_menu 'options[@]')
-for i in "${!options[@]}"; do
-  if [ "${options[$i]}" = "${install_selection}" ]; then
-    install_type="${i}";
+  # Download/update dotfiles only if we're not running with a restart after
+  # already updating
+  if [ "$1" != restart ]; then
+    fetch_dotfiles || {
+      echo "Dotfiles were updated. Restarting..."
+      exec "$0" "restart"
+    }
   fi
-done
 
-# Execute code for each file in these subdirectories.
-do_stuff "copy"
-do_stuff "link"
-do_stuff "init"
+  "init_$os"
+  install_things "$os"
 
-# Alert if backups were made.
-if [[ "$backup" ]]; then
-  echo -e "\nBackups were moved to ~/${backup_dir#$HOME/}"
-fi
+  # Alert if backups were made.
+  if [ -e "$BACKUPS" ]; then
+    printf -- "\\nBackups were moved to ~/%s\\n" "${BACKUPS#$HOME/}"
+  fi
 
-# All done!
-e_header "Note: You may need to log out and back in."
-e_header "All done!"
+  # All done!
+  log_header "Note: You may need to log out and back in."
+  log_header "Siiiick! You're ready to go! (•̀ᴗ•́)و"
+}
+
+main "$@"
